[2024-11-05T17:41:11.933+0000] {processor.py:186} INFO - Started process (PID=83) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:41:11.936+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:41:11.953+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:41:11.943+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:41:14.072+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:41:16.959+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:41:16.989+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:41:16.973+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:41:16.998+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:41:17.065+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 5.163 seconds
[2024-11-05T17:41:47.278+0000] {processor.py:186} INFO - Started process (PID=166) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:41:47.280+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:41:47.283+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:41:47.282+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:41:48.971+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:41:51.300+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:41:51.314+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:41:51.305+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:41:51.318+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:41:51.340+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 4.070 seconds
[2024-11-05T17:42:21.655+0000] {processor.py:186} INFO - Started process (PID=246) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:42:21.658+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:42:21.663+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:42:21.662+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:42:23.730+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:42:25.322+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:42:25.336+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:42:25.327+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:42:25.341+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:42:25.372+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.736 seconds
[2024-11-05T17:42:56.009+0000] {processor.py:186} INFO - Started process (PID=324) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:42:56.012+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:42:56.017+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:42:56.017+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:42:58.942+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:43:00.546+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:43:00.560+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:43:00.551+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:43:00.565+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:43:00.587+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 4.590 seconds
[2024-11-05T17:43:31.487+0000] {processor.py:186} INFO - Started process (PID=397) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:43:31.490+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:43:31.499+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:43:31.498+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:43:34.034+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:43:35.682+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:43:35.722+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:43:35.709+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:43:35.727+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:43:35.753+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 4.292 seconds
[2024-11-05T17:44:06.777+0000] {processor.py:186} INFO - Started process (PID=460) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:44:06.780+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:44:06.788+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:44:06.787+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:44:08.588+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:44:10.027+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:44:10.047+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:44:10.037+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:44:10.051+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:44:10.079+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.321 seconds
[2024-11-05T17:44:40.297+0000] {processor.py:186} INFO - Started process (PID=523) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:44:40.299+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:44:40.304+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:44:40.303+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:44:42.292+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:44:43.707+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:44:43.728+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:44:43.718+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:44:43.733+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:44:43.763+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.474 seconds
[2024-11-05T17:45:13.838+0000] {processor.py:186} INFO - Started process (PID=586) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:45:13.840+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:45:13.844+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:45:13.843+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:45:15.822+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:45:17.333+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:45:17.347+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:45:17.339+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:45:17.351+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:45:17.373+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.545 seconds
[2024-11-05T17:45:48.103+0000] {processor.py:186} INFO - Started process (PID=658) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:45:48.105+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:45:48.113+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:45:48.112+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:45:50.345+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:45:51.859+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:45:51.879+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:45:51.870+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:45:51.883+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:45:51.910+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.824 seconds
[2024-11-05T17:46:22.231+0000] {processor.py:186} INFO - Started process (PID=730) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:46:22.233+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:46:22.237+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:46:22.236+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:46:23.915+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:46:25.324+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:46:25.339+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:46:25.331+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:46:25.344+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:46:25.371+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.150 seconds
[2024-11-05T17:46:55.848+0000] {processor.py:186} INFO - Started process (PID=801) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:46:55.849+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:46:55.852+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:46:55.852+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:46:58.633+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:47:00.095+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:47:00.109+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:47:00.101+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:47:00.114+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:47:00.136+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 4.297 seconds
[2024-11-05T17:47:30.330+0000] {processor.py:186} INFO - Started process (PID=873) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:47:30.332+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:47:30.338+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:47:30.337+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:47:32.552+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:47:34.021+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:47:34.036+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:47:34.027+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:47:34.040+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:47:34.064+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.746 seconds
[2024-11-05T17:48:04.136+0000] {processor.py:186} INFO - Started process (PID=951) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:48:04.138+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:48:04.141+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:48:04.141+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:48:05.852+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:48:07.579+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:48:07.631+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:48:07.601+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:48:07.646+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:48:07.748+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.620 seconds
[2024-11-05T17:48:38.073+0000] {processor.py:186} INFO - Started process (PID=1026) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:48:38.074+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:48:38.079+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:48:38.078+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:48:40.027+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:48:41.505+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:48:41.523+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:48:41.512+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:48:41.528+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:48:41.562+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.502 seconds
[2024-11-05T17:49:11.688+0000] {processor.py:186} INFO - Started process (PID=1089) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:49:11.690+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:49:11.695+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:49:11.694+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:49:13.695+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:49:15.114+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:49:15.132+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:49:15.122+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:49:15.138+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:49:15.171+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.494 seconds
[2024-11-05T17:49:45.881+0000] {processor.py:186} INFO - Started process (PID=1152) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:49:45.884+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:49:45.891+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:49:45.890+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:49:47.749+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:49:49.347+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:49:49.380+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:49:49.367+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:49:49.387+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:49:49.420+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.556 seconds
[2024-11-05T17:50:19.969+0000] {processor.py:186} INFO - Started process (PID=1222) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:50:19.973+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:50:19.982+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:50:19.981+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:50:22.140+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:50:23.611+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:50:23.658+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:50:23.637+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:50:23.672+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:50:23.733+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.786 seconds
[2024-11-05T17:50:53.897+0000] {processor.py:186} INFO - Started process (PID=1285) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:50:53.899+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:50:53.904+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:50:53.904+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:50:55.487+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:50:56.998+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:50:57.029+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:50:57.013+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:50:57.038+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:50:57.083+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.196 seconds
[2024-11-05T17:51:27.268+0000] {processor.py:186} INFO - Started process (PID=1352) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:51:27.270+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:51:27.274+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:51:27.274+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:51:29.078+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:51:30.596+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:51:30.623+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:51:30.609+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:51:30.632+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:51:30.671+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.417 seconds
[2024-11-05T17:52:00.940+0000] {processor.py:186} INFO - Started process (PID=1423) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:52:00.943+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:52:00.949+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:52:00.948+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:52:02.652+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:52:04.106+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:52:04.127+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:52:04.116+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:52:04.133+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:52:04.189+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.268 seconds
[2024-11-05T17:52:34.324+0000] {processor.py:186} INFO - Started process (PID=1494) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:52:34.325+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:52:34.330+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:52:34.329+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:52:56.861+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:52:58.273+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:52:58.289+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:52:58.279+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:52:58.295+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:52:58.320+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 24.007 seconds
[2024-11-05T17:53:28.475+0000] {processor.py:186} INFO - Started process (PID=1603) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:53:28.476+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:53:28.479+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:53:28.479+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:53:30.207+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:53:31.666+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:53:31.682+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:53:31.673+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:53:31.687+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:53:31.717+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.250 seconds
[2024-11-05T17:54:02.456+0000] {processor.py:186} INFO - Started process (PID=1669) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:54:02.459+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:54:02.465+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:54:02.464+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:54:04.164+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:54:05.735+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:54:05.761+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:54:05.749+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:54:05.768+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:54:05.821+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.384 seconds
[2024-11-05T17:54:36.542+0000] {processor.py:186} INFO - Started process (PID=1742) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:54:36.545+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:54:36.551+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:54:36.550+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:54:38.755+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:54:40.216+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:54:40.242+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:54:40.224+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:54:40.248+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:54:40.320+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.801 seconds
[2024-11-05T17:55:10.619+0000] {processor.py:186} INFO - Started process (PID=1813) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:55:10.621+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:55:10.629+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:55:10.628+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:55:12.601+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:55:14.271+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:55:14.322+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:55:14.299+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:55:14.334+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:55:14.410+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.808 seconds
[2024-11-05T17:55:44.840+0000] {processor.py:186} INFO - Started process (PID=1876) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:55:44.841+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:55:44.846+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:55:44.845+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:55:46.882+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:55:48.374+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:55:48.392+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:55:48.382+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:55:48.396+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:55:48.422+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.591 seconds
[2024-11-05T17:56:18.684+0000] {processor.py:186} INFO - Started process (PID=1943) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:56:18.686+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:56:18.690+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:56:18.689+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:56:21.004+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:56:22.526+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:56:22.544+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:56:22.536+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:56:22.549+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:56:22.578+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.904 seconds
[2024-11-05T17:56:53.640+0000] {processor.py:186} INFO - Started process (PID=2024) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:56:53.642+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:56:53.648+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:56:53.648+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:56:55.670+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:56:57.253+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:56:57.272+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:56:57.262+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:56:57.279+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:56:57.309+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.683 seconds
[2024-11-05T17:57:27.602+0000] {processor.py:186} INFO - Started process (PID=2102) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:57:27.603+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:57:27.606+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:57:27.605+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:57:29.675+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:57:31.122+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:57:31.136+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:57:31.127+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:57:31.143+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:57:31.175+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.580 seconds
[2024-11-05T17:58:02.146+0000] {processor.py:186} INFO - Started process (PID=2165) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:58:02.147+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:58:02.151+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:58:02.151+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:58:03.770+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:58:05.291+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:58:05.316+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:58:05.301+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:58:05.324+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:58:05.367+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.233 seconds
[2024-11-05T17:58:36.448+0000] {processor.py:186} INFO - Started process (PID=2235) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:58:36.450+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:58:36.456+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:58:36.456+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:58:38.222+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:58:39.696+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:58:39.715+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:58:39.704+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:58:39.721+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:58:39.745+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.312 seconds
[2024-11-05T17:59:10.488+0000] {processor.py:186} INFO - Started process (PID=2304) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:59:10.490+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:59:10.492+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:59:10.492+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:59:12.623+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:59:14.142+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:59:14.165+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:59:14.150+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:59:14.169+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:59:14.206+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.725 seconds
[2024-11-05T17:59:44.319+0000] {processor.py:186} INFO - Started process (PID=2377) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:59:44.321+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T17:59:44.324+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:59:44.323+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:59:46.936+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T17:59:48.466+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T17:59:48.485+0000] {logging_mixin.py:190} INFO - [2024-11-05T17:59:48.474+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T17:59:48.490+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T17:59:48.518+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 4.206 seconds
[2024-11-05T18:00:19.050+0000] {processor.py:186} INFO - Started process (PID=2442) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:00:19.051+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:00:19.055+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:00:19.055+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:00:21.120+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:00:22.734+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:00:22.764+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:00:22.747+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:00:22.772+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:00:22.815+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.774 seconds
[2024-11-05T18:00:53.726+0000] {processor.py:186} INFO - Started process (PID=2512) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:00:53.727+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:00:53.731+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:00:53.731+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:00:55.542+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:00:57.051+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:00:57.068+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:00:57.058+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:00:57.074+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:00:57.101+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.386 seconds
[2024-11-05T18:01:27.247+0000] {processor.py:186} INFO - Started process (PID=2577) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:01:27.248+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:01:27.252+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:01:27.251+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:01:30.251+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:01:32.297+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:01:32.312+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:01:32.304+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:01:32.316+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:01:32.346+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 5.108 seconds
[2024-11-05T18:02:02.466+0000] {processor.py:186} INFO - Started process (PID=2665) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:02:02.468+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:02:02.477+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:02:02.475+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:02:04.213+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:02:05.739+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:02:05.753+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:02:05.745+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:02:05.757+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:02:05.780+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.335 seconds
[2024-11-05T18:02:35.908+0000] {processor.py:186} INFO - Started process (PID=2731) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:02:35.910+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:02:35.915+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:02:35.914+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:02:38.029+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:02:39.472+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:02:39.486+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:02:39.478+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:02:39.490+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:02:39.512+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.617 seconds
[2024-11-05T18:03:09.745+0000] {processor.py:186} INFO - Started process (PID=2798) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:03:09.746+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:03:09.749+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:03:09.749+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:03:12.302+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:03:14.055+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:03:14.069+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:03:14.060+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:03:14.073+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:03:14.095+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 4.361 seconds
[2024-11-05T18:03:44.245+0000] {processor.py:186} INFO - Started process (PID=2870) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:03:44.247+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:03:44.251+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:03:44.250+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:03:46.236+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:03:47.713+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:03:47.734+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:03:47.724+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:03:47.739+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:03:47.765+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.528 seconds
[2024-11-05T18:04:18.000+0000] {processor.py:186} INFO - Started process (PID=2936) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:04:18.003+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:04:18.007+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:04:18.007+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:04:19.826+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:04:21.284+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:04:21.298+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:04:21.290+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:04:21.306+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:04:21.346+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.361 seconds
[2024-11-05T18:04:51.451+0000] {processor.py:186} INFO - Started process (PID=3005) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:04:51.454+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:04:51.459+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:04:51.459+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:04:53.514+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:04:54.937+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:04:54.951+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:04:54.943+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:04:54.955+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:04:54.981+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.544 seconds
[2024-11-05T18:05:25.089+0000] {processor.py:186} INFO - Started process (PID=3076) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:05:25.091+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:05:25.094+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:05:25.094+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:05:27.406+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:05:28.930+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:05:28.946+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:05:28.938+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:05:28.957+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:05:28.983+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.901 seconds
[2024-11-05T18:05:59.330+0000] {processor.py:186} INFO - Started process (PID=3140) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:05:59.331+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:05:59.335+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:05:59.334+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:06:01.045+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:06:02.546+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:06:02.569+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:06:02.558+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:06:02.575+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:06:02.603+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.282 seconds
[2024-11-05T18:06:33.126+0000] {processor.py:186} INFO - Started process (PID=3204) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:06:33.128+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:06:33.131+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:06:33.130+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:06:35.494+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:06:37.061+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:06:37.081+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:06:37.072+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:06:37.086+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:06:37.114+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.995 seconds
[2024-11-05T18:07:07.772+0000] {processor.py:186} INFO - Started process (PID=3267) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:07:07.774+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:07:07.777+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:07:07.777+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:07:09.683+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:07:11.095+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:07:11.108+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:07:11.101+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:07:11.112+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:07:11.134+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.373 seconds
[2024-11-05T18:07:41.295+0000] {processor.py:186} INFO - Started process (PID=3338) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:07:41.296+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:07:41.300+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:07:41.300+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:07:42.936+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:07:44.386+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:07:44.400+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:07:44.392+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:07:44.404+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:07:44.427+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.141 seconds
[2024-11-05T18:08:14.561+0000] {processor.py:186} INFO - Started process (PID=3412) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:08:14.562+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:08:14.565+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:08:14.565+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:08:16.671+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:08:18.464+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:08:18.670+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:08:18.660+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:08:18.676+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:08:18.715+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 4.161 seconds
[2024-11-05T18:08:49.613+0000] {processor.py:186} INFO - Started process (PID=3493) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:08:49.615+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:08:49.618+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:08:49.617+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:08:51.898+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:08:53.396+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:08:53.415+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:08:53.403+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:08:53.420+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:08:53.445+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.840 seconds
[2024-11-05T18:09:23.908+0000] {processor.py:186} INFO - Started process (PID=3571) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:09:23.910+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:09:23.914+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:09:23.914+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:09:26.444+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:09:27.929+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:09:27.942+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:09:27.934+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:09:27.947+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:09:27.968+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 4.075 seconds
[2024-11-05T18:09:58.509+0000] {processor.py:186} INFO - Started process (PID=3634) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:09:58.512+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:09:58.516+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:09:58.515+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:10:00.861+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:10:02.310+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:10:02.324+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:10:02.316+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:10:02.328+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:10:02.560+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 4.070 seconds
[2024-11-05T18:10:32.665+0000] {processor.py:186} INFO - Started process (PID=3697) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:10:32.667+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:10:32.670+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:10:32.670+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:10:39.522+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:10:41.137+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:10:41.158+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:10:41.147+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:10:41.163+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:10:41.205+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 8.551 seconds
[2024-11-05T18:11:11.926+0000] {processor.py:186} INFO - Started process (PID=3770) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:11:11.930+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:11:11.933+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:11:11.933+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:11:13.621+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:11:15.196+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:11:15.210+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:11:15.201+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:11:15.214+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:11:15.238+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.319 seconds
[2024-11-05T18:11:45.562+0000] {processor.py:186} INFO - Started process (PID=3833) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:11:45.563+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:11:45.566+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:11:45.565+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:11:47.340+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:11:48.830+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:11:48.843+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:11:48.835+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:11:48.847+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:11:48.870+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.315 seconds
[2024-11-05T18:12:19.389+0000] {processor.py:186} INFO - Started process (PID=3903) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:12:19.390+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:12:19.395+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:12:19.394+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:12:21.045+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:12:22.544+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:12:22.559+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:12:22.550+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:12:22.563+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:12:22.591+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.210 seconds
[2024-11-05T18:12:53.058+0000] {processor.py:186} INFO - Started process (PID=3987) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:12:53.059+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:12:53.063+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:12:53.062+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:12:54.936+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:12:56.399+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:12:56.411+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:12:56.404+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:12:56.415+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:12:56.438+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.389 seconds
[2024-11-05T18:13:27.034+0000] {processor.py:186} INFO - Started process (PID=4062) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:13:27.036+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:13:27.039+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:13:27.039+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:13:29.226+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:13:30.718+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:13:30.731+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:13:30.722+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:13:30.735+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:13:30.757+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.731 seconds
[2024-11-05T18:14:00.849+0000] {processor.py:186} INFO - Started process (PID=4137) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:14:00.850+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:14:00.854+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:14:00.854+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:14:02.744+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:14:04.312+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:14:04.326+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:14:04.317+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:14:04.331+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:14:04.354+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.512 seconds
[2024-11-05T18:14:34.588+0000] {processor.py:186} INFO - Started process (PID=4200) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:14:34.589+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:14:34.592+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:14:34.591+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:14:36.312+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:14:37.801+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:14:37.819+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:14:37.808+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:14:37.825+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:14:37.854+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.274 seconds
[2024-11-05T18:15:08.240+0000] {processor.py:186} INFO - Started process (PID=4263) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:15:08.241+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:15:08.245+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:15:08.244+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:15:10.300+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:15:11.775+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:15:11.789+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:15:11.780+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:15:11.793+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:15:11.815+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.585 seconds
[2024-11-05T18:15:42.136+0000] {processor.py:186} INFO - Started process (PID=4332) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:15:42.138+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:15:42.141+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:15:42.141+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:15:43.816+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:15:45.324+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:15:45.343+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:15:45.332+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:15:45.348+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:15:45.378+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.249 seconds
[2024-11-05T18:16:15.523+0000] {processor.py:186} INFO - Started process (PID=4400) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:16:15.524+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:16:15.528+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:16:15.527+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:16:17.441+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:16:18.906+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:16:18.930+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:16:18.916+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:16:18.936+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:16:18.972+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.459 seconds
[2024-11-05T18:16:49.759+0000] {processor.py:186} INFO - Started process (PID=4463) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:16:49.761+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:16:49.764+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:16:49.763+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:16:51.744+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:16:53.161+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:16:53.175+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:16:53.167+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:16:53.180+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:16:53.203+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.451 seconds
[2024-11-05T18:17:23.383+0000] {processor.py:186} INFO - Started process (PID=4537) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:17:23.384+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:17:23.387+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:17:23.387+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:17:25.843+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:17:27.670+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:17:27.684+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:17:27.675+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:17:27.688+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:17:27.709+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 4.333 seconds
[2024-11-05T18:17:58.277+0000] {processor.py:186} INFO - Started process (PID=4608) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:17:58.278+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:17:58.281+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:17:58.281+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:18:00.089+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:18:01.576+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:18:01.590+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:18:01.581+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:18:01.594+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:18:01.616+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.346 seconds
[2024-11-05T18:18:32.009+0000] {processor.py:186} INFO - Started process (PID=4685) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:18:32.011+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:18:32.014+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:18:32.014+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:18:33.632+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:18:35.293+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:18:35.315+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:18:35.303+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:18:35.320+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:18:35.348+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.347 seconds
[2024-11-05T18:19:06.149+0000] {processor.py:186} INFO - Started process (PID=4767) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:19:06.150+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:19:06.154+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:19:06.153+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:19:08.065+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:19:09.553+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:19:09.568+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:19:09.558+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:19:09.572+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:19:09.599+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.463 seconds
[2024-11-05T18:19:40.206+0000] {processor.py:186} INFO - Started process (PID=4830) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:19:40.208+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:19:40.211+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:19:40.210+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:19:41.932+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:19:43.443+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:19:43.459+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:19:43.449+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:19:43.464+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:19:43.501+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.302 seconds
[2024-11-05T18:20:13.934+0000] {processor.py:186} INFO - Started process (PID=4893) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:20:13.935+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:20:13.938+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:20:13.938+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:20:15.777+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:20:17.196+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:20:17.210+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:20:17.202+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:20:17.215+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:20:17.243+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.316 seconds
[2024-11-05T18:20:47.922+0000] {processor.py:186} INFO - Started process (PID=4956) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:20:47.923+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:20:47.927+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:20:47.926+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:20:49.616+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:20:51.176+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:20:51.193+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:20:51.183+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:20:51.197+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:20:51.220+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.306 seconds
[2024-11-05T18:21:21.456+0000] {processor.py:186} INFO - Started process (PID=5029) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:21:21.457+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:21:21.460+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:21:21.460+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:21:23.924+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:21:25.413+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:21:25.435+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:21:25.424+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:21:25.440+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:21:25.468+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 4.021 seconds
[2024-11-05T18:21:56.119+0000] {processor.py:186} INFO - Started process (PID=5099) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:21:56.121+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:21:56.124+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:21:56.124+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:21:58.126+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:21:59.628+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:21:59.642+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:21:59.633+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:21:59.646+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:21:59.667+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.557 seconds
[2024-11-05T18:22:29.906+0000] {processor.py:186} INFO - Started process (PID=5162) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:22:29.908+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:22:29.912+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:22:29.911+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:22:31.919+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:22:33.434+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:22:33.448+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:22:33.439+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:22:33.452+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:22:33.476+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.579 seconds
[2024-11-05T18:23:03.951+0000] {processor.py:186} INFO - Started process (PID=5234) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:23:03.953+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:23:03.958+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:23:03.957+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:23:05.819+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:23:07.266+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:23:07.290+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:23:07.276+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:23:07.300+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:23:07.345+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.409 seconds
[2024-11-05T18:23:37.983+0000] {processor.py:186} INFO - Started process (PID=5307) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:23:37.987+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:23:38.004+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:23:38.000+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:23:40.167+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:23:41.673+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:23:41.697+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:23:41.684+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:23:41.730+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:23:41.817+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.859 seconds
[2024-11-05T18:24:12.871+0000] {processor.py:186} INFO - Started process (PID=5381) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:24:12.875+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:24:12.885+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:24:12.883+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:24:15.542+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:24:17.159+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:24:17.234+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:24:17.193+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:24:17.255+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:24:17.422+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 4.578 seconds
[2024-11-05T18:24:48.115+0000] {processor.py:186} INFO - Started process (PID=5451) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:24:48.116+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:24:48.119+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:24:48.119+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:24:49.934+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:24:53.396+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:24:53.411+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:24:53.403+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:24:53.419+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:24:53.445+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 5.340 seconds
[2024-11-05T18:25:23.867+0000] {processor.py:186} INFO - Started process (PID=5529) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:25:23.869+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:25:23.872+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:25:23.872+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:25:25.899+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:25:27.403+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:25:27.415+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:25:27.408+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:25:27.419+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:25:27.441+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.581 seconds
[2024-11-05T18:25:57.646+0000] {processor.py:186} INFO - Started process (PID=5596) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:25:57.647+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:25:57.651+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:25:57.650+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:25:59.918+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:26:01.511+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:26:01.527+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:26:01.517+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:26:01.532+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:26:01.561+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.922 seconds
[2024-11-05T18:26:31.982+0000] {processor.py:186} INFO - Started process (PID=5665) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:26:31.983+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:26:31.987+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:26:31.986+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:26:33.785+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:26:35.297+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:26:35.310+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:26:35.303+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:26:35.314+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:26:35.337+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.362 seconds
[2024-11-05T18:27:06.108+0000] {processor.py:186} INFO - Started process (PID=5728) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:27:06.110+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:27:06.113+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:27:06.113+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:27:08.351+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:27:09.933+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:27:09.958+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:27:09.942+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:27:09.965+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:27:10.004+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.905 seconds
[2024-11-05T18:27:40.873+0000] {processor.py:186} INFO - Started process (PID=5802) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:27:40.875+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:27:40.878+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:27:40.877+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:27:42.900+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:27:44.404+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:27:44.419+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:27:44.411+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:27:44.424+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:27:44.447+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.583 seconds
[2024-11-05T18:28:14.640+0000] {processor.py:186} INFO - Started process (PID=5874) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:28:14.641+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:28:14.644+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:28:14.644+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:28:16.619+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:28:18.050+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:28:18.063+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:28:18.055+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:28:18.067+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:28:18.090+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.459 seconds
[2024-11-05T18:28:48.200+0000] {processor.py:186} INFO - Started process (PID=5944) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:28:48.201+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:28:48.205+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:28:48.205+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:28:50.174+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:28:51.722+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:28:51.736+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:28:51.727+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:28:51.740+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:28:51.763+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.573 seconds
[2024-11-05T18:29:22.759+0000] {processor.py:186} INFO - Started process (PID=6016) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:29:22.762+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:29:22.766+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:29:22.765+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:29:25.589+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:29:27.195+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:29:27.210+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:29:27.201+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:29:27.215+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:29:27.242+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 4.499 seconds
[2024-11-05T18:29:58.254+0000] {processor.py:186} INFO - Started process (PID=6095) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:29:58.257+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:29:58.263+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:29:58.262+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:30:00.215+0000] {logging_mixin.py:190} INFO - Connection successful!
[2024-11-05T18:30:01.739+0000] {logging_mixin.py:190} INFO - data loaded successfully
[2024-11-05T18:30:01.761+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:30:01.749+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/newyorktrip_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newyorktrip_etl_dag.py", line 54, in <module>
    docker
NameError: name 'docker' is not defined
[2024-11-05T18:30:01.774+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:30:01.817+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/newyorktrip_etl_dag.py took 3.581 seconds
[2024-11-05T18:30:32.326+0000] {processor.py:186} INFO - Started process (PID=6158) to work on /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:30:32.328+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/newyorktrip_etl_dag.py for tasks to queue
[2024-11-05T18:30:32.332+0000] {logging_mixin.py:190} INFO - [2024-11-05T18:30:32.331+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/newyorktrip_etl_dag.py
[2024-11-05T18:30:34.058+0000] {logging_mixin.py:190} INFO - Connection successful!
